services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_BASE_URL=${API_BASE_URL:-https://your-api-domain.com}
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    command: bun run dev
